In [29]:
import numpy as np
import random
from time import time
from math import sin, cos
from PIL import Image
import matplotlib.pyplot as plt

In [30]:
# Zadanie 1

@timeit
def random_tab():
    tab=[]
    for i in range(10000):
        tab.append(random.randint(0, 10000))

    for i in range(len(tab)):
        tab[i] += 1

    return tab

@timeit
def random_tab_numpy():
    tab = np.random.randint(0, 10000, size=(10000, 1))
    tab += 1
    return tab.flatten()

tab1=random_tab()
tab2=random_tab_numpy()

0.031000137329101562
0.0009999275207519531


In [19]:
#zadanie 2

@timeit
def sin_cos():
    tab = random_tab()
    result_tab = np.zeros_like(tab)

    for i in range(len(tab)):
        result_tab[i] = sin(tab[i]) + cos(tab[i])

    return result_tab


@timeit
def sin_cos_numpy():
    tab=random_tab_numpy()

    def sin_cos_function(x):
        return sin(x)+cos(x)

    vectorized_function=np.vectorize(sin_cos_function)

    result_tab=vectorized_function(tab)

    return result_tab


tab_sin_cos = sin_cos()
tab_sin_cos_numpy = sin_cos_numpy()

0.03300023078918457
0.05000019073486328
0.0009999275207519531
0.015000104904174805


In [31]:
#zadanie 3

@timeit
def cube_sum(x):
    """Zwraca sumę sześcianów elementów"""
    result = 0
    for i in range(len(x)):
        result += x[i] ** 3
    return result

@timeit
def almost_variance(x):
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    m = sum(x) / len(x)
    result = 0
    for i in range(len(x)):
        result += (x[i] - m) ** 4
    result /= len(x)
    return result

@timeit
def cube_sum_numpy(x):
    """Zwraca sumę sześcianów elementów"""
    return np.sum(x**3)

@timeit
def almost_variance_numpy(x):
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    m = np.mean(x)
    return np.mean((x - m)**4)

arr1 = np.random.rand(10000)

result_cube_sum = cube_sum(arr1)
result_almost_variance = almost_variance(arr1)

result_cube_sum_numpy = cube_sum_numpy(arr1)
result_almost_variance_numpy = almost_variance_numpy(arr1)

0.009000062942504883
0.013000011444091797
0.0009999275207519531
0.0010001659393310547


In [32]:
#zadanie 4

multiplication_table = np.arange(1, 11)[:, None] * np.arange(1, 11)
print(multiplication_table)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [22]:
#zadanie 5

points = np.random.rand(10, 5)

distances = np.linalg.norm(points[:, np.newaxis, :] - points[np.newaxis, :, :], axis=2)

print(distances)

[[0.         0.6479069  0.61791849 1.17729121 0.68171569 0.43944365
  0.63757794 0.72343737 0.92006602 0.65249451]
 [0.6479069  0.         0.47823803 1.19525643 0.49160048 0.55498224
  0.43254579 0.68243151 0.60408623 0.62752978]
 [0.61791849 0.47823803 0.         1.2326722  0.75310522 0.78445138
  0.54406787 0.89802358 0.78159455 0.81264412]
 [1.17729121 1.19525643 1.2326722  0.         0.86478183 1.01571792
  0.89574838 1.0295439  1.09349034 0.99799256]
 [0.68171569 0.49160048 0.75310522 0.86478183 0.         0.44607565
  0.26471868 0.40140731 0.42531665 0.70333231]
 [0.43944365 0.55498224 0.78445138 1.01571792 0.44607565 0.
  0.52835501 0.64013105 0.82636075 0.52401867]
 [0.63757794 0.43254579 0.54406787 0.89574838 0.26471868 0.52835501
  0.         0.56112012 0.42208706 0.75634869]
 [0.72343737 0.68243151 0.89802358 1.0295439  0.40140731 0.64013105
  0.56112012 0.         0.48221702 0.81866735]
 [0.92006602 0.60408623 0.78159455 1.09349034 0.42531665 0.82636075
  0.42208706 0.48221

In [23]:
#zadanie 6

def whiten_data(points):
    mean_values = np.mean(points, axis=0)
    std_deviation = np.std(points, axis=0)
    whitened_points = (points - mean_values) / std_deviation

    return whitened_points


sample_data = np.array([[0, 1],
                        [2, 3],
                        [4, 5],
                        [6, 7],
                        [8, 9],
                        ])

whitened_data = whiten_data(sample_data)
print(whitened_data)

[[-1.41421356 -1.41421356]
 [-0.70710678 -0.70710678]
 [ 0.          0.        ]
 [ 0.70710678  0.70710678]
 [ 1.41421356  1.41421356]]


In [24]:
#zadanie 7

A = [1, -4, 3]
x = 1.5
result = min(A, key=lambda a: abs(x - a))
print(result)

1


In [25]:
#zadanie 8

def evaluate_polynomial(x, coefficients):
    return np.sum(np.cumprod([1] + [x] * (len(coefficients) - 1)) * coefficients)

coefficients = [2, 3, 1]
x_value = 1
result = evaluate_polynomial(x_value, coefficients)
print(result)

6


In [ ]:
#zadanie 9

def rgb_to_grayscale(img_path):
    img = Image.open(img_path)

    img_array = np.array(img)

    grayscale_img_array = 0.2126 * img_array[:, :, 0] + 0.7152 * img_array[:, :, 1] + 0.0722 * img_array[:, :, 2]

    grayscale_img = Image.fromarray(grayscale_img_array.astype('uint8'))

    return grayscale_img

img_path = r'C:\Users\doria\Downloads\doggo.png'
grayscale_img = rgb_to_grayscale(img_path)

plt.imshow(grayscale_img, cmap='gray')
plt.axis('off')
plt.show()

In [33]:
#zadanie 10

def linear_interpolation(point1, point2, values):
    values = np.asarray(values)
    t = (values - point1[0]) / (point2[0] - point1[0])
    result = point1[1] + t * (point2[1] - point1[1])
    return result

point1 = np.array([1, 2])
point2 = np.array([4, 6])
values = np.linspace(0, 1, 10)

interpolated_values = linear_interpolation(point1, point2, values)
print(interpolated_values)


[0.66666667 0.81481481 0.96296296 1.11111111 1.25925926 1.40740741
 1.55555556 1.7037037  1.85185185 2.        ]
